"""add_patient_id_to_audit_events

Revision ID: 8d254f062da3
Revises: a73fc8a503aa
Create Date: 2026-10-04 00:02:17.299840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d254f062da3'
down_revision: Union[str, Sequence[str], None] = 'a73fc8a503aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_auth_audit_events_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_audit_events_patient_id'))
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
