"""add_clinical_models

Revision ID: a73fc8a503aa
Revises: ff7896daaf32
Create Date: 2026-10-04 00:00:30.484089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73fc8a503aa'
down_revision: Union[str, Sequence[str], None] = 'ff7896daaf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('mrn', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dob', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.String(length=32), nullable=False),
    sa.Column('blood_type', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('insurance_provider', sa.String(length=160), nullable=True),
    sa.Column('policy_number', sa.String(length=64), nullable=True),
    sa.Column('attending_physician_id', sa.String(length=36), nullable=True),
    sa.Column('ward', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('admitted', 'discharge_pending', 'discharged')", name='ck_patient_status'),
    sa.ForeignKeyConstraint(['attending_physician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'mrn', name='uq_workspace_patient_mrn')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_attending_physician_id'), ['attending_physician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_mrn'), ['mrn'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('allergies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('allergen', sa.String(length=160), nullable=False),
    sa.Column('noted_by_id', sa.String(length=36), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['noted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergies_noted_by_id'), ['noted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allergies_patient_id'), ['patient_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('with_provider_id', sa.String(length=36), nullable=True),
    sa.Column('with_provider_name', sa.String(length=160), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_by_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('upcoming', 'completed', 'cancelled')", name='ck_appointment_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['with_provider_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_scheduled_by_id'), ['scheduled_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_with_provider_id'), ['with_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('discharge_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_by_id', sa.String(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'signed')", name='ck_discharge_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discharge_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discharge_drafts_patient_id'), ['patient_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_discharge_drafts_signed_by_id'), ['signed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discharge_drafts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_file_url', sa.String(length=512), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'needs_review', 'processed')", name='ck_document_status'),
    sa.CheckConstraint("type IN ('lab_report', 'clinical_note', 'intake_form', 'referral_letter', 'insurance_claim', 'prescription', 'discharge_summary')", name='ck_document_type'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by_id'), ['uploaded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('immunizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=160), nullable=False),
    sa.Column('administered_date', sa.String(length=32), nullable=False),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immunizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immunizations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_immunizations_recorded_by_id'), ['recorded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_immunizations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('lab_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_tests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dose', sa.String(length=64), nullable=False),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.Column('flag_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("flag IS NULL OR flag IN ('none', 'interaction', 'dosage')", name='ck_medication_flag'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('vitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('bp', sa.String(length=32), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vitals_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vitals_recorded_by_id'), ['recorded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vitals_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('discharge_paragraphs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discharge_draft_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_citation', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discharge_draft_id'], ['discharge_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discharge_paragraphs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discharge_paragraphs_discharge_draft_id'), ['discharge_draft_id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_confirmed_by_id'), ['confirmed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)

    op.create_table('lab_result_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_test_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_result_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_result_points_lab_test_id'), ['lab_test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_result_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_result_points_lab_test_id'))

    op.drop_table('lab_result_points')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_confirmed_by_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('discharge_paragraphs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discharge_paragraphs_discharge_draft_id'))

    op.drop_table('discharge_paragraphs')
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_vitals_recorded_by_id'))
        batch_op.drop_index(batch_op.f('ix_vitals_patient_id'))

    op.drop_table('vitals')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_medications_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_medications_patient_id'))

    op.drop_table('medications')
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_patient_id'))

    op.drop_table('lab_tests')
    with op.batch_alter_table('immunizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immunizations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_immunizations_recorded_by_id'))
        batch_op.drop_index(batch_op.f('ix_immunizations_patient_id'))

    op.drop_table('immunizations')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_documents_patient_id'))

    op.drop_table('documents')
    with op.batch_alter_table('discharge_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discharge_drafts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_discharge_drafts_signed_by_id'))
        batch_op.drop_index(batch_op.f('ix_discharge_drafts_patient_id'))

    op.drop_table('discharge_drafts')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_with_provider_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_scheduled_by_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allergies_patient_id'))
        batch_op.drop_index(batch_op.f('ix_allergies_noted_by_id'))

    op.drop_table('allergies')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_mrn'))
        batch_op.drop_index(batch_op.f('ix_patients_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_patients_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_patients_attending_physician_id'))

    op.drop_table('patients')
    # ### end Alembic commands ###
