"""Pydantic request and response contracts."""

from app.schemas.auth import AuthResponse, LoginRequest, PermissionResponse, RegisterRequest, RoleName, StrongPassword
from app.schemas.clinical import (
    AllergyCreate,
    AllergyOut,
    AppointmentCreate,
    AppointmentOut,
    AuditEventListOut,
    AuditEventOut,
    DashboardStatsOut,
    DischargeDraftCreate,
    DischargeDraftOut,
    DischargeParagraphCreate,
    DischargeParagraphOut,
    DocumentCreate,
    DocumentOut,
    ExtractedFieldCreate,
    ExtractedFieldOut,
    ImmunizationCreate,
    ImmunizationOut,
    LabResultPointCreate,
    LabResultPointOut,
    LabTestCreate,
    LabTestOut,
    MedicationCreate,
    MedicationOut,
    PatientCreate,
    PatientListOut,
    PatientOut,
    PatientUpdate,
    VitalsCreate,
    VitalsOut,
)
from app.schemas.common import HealthResponse, MessageResponse
from app.schemas.users import UserListResponse, UserResponse, UserRoleUpdate, UserStatusUpdate

__all__ = [
    "AllergyCreate",
    "AllergyOut",
    "AppointmentCreate",
    "AppointmentOut",
    "AuditEventListOut",
    "AuditEventOut",
    "AuthResponse",
    "DashboardStatsOut",
    "DischargeDraftCreate",
    "DischargeDraftOut",
    "DischargeParagraphCreate",
    "DischargeParagraphOut",
    "DocumentCreate",
    "DocumentOut",
    "ExtractedFieldCreate",
    "ExtractedFieldOut",
    "HealthResponse",
    "ImmunizationCreate",
    "ImmunizationOut",
    "LabResultPointCreate",
    "LabResultPointOut",
    "LabTestCreate",
    "LabTestOut",
    "LoginRequest",
    "MedicationCreate",
    "MedicationOut",
    "MessageResponse",
    "PatientCreate",
    "PatientListOut",
    "PatientOut",
    "PatientUpdate",
    "PermissionResponse",
    "RegisterRequest",
    "RoleName",
    "StrongPassword",
    "UserListResponse",
    "UserResponse",
    "UserRoleUpdate",
    "UserStatusUpdate",
    "VitalsCreate",
    "VitalsOut",
]